CREATE TABLE IF NOT EXISTS enviro_items (
  id SERIAL PRIMARY KEY,
  source TEXT,
  type TEXT,
  title TEXT,
  date DATE,
  listed_date DATE,
  region TEXT,
  municipality TEXT,
  okres TEXT,
  phase TEXT,
  cpv JSONB,
  buyer TEXT,
  value NUMERIC,
  detail_url TEXT UNIQUE,
  source_url TEXT,
  has_pdf BOOLEAN,
  raw_text_snippet TEXT,
  fetched_at TIMESTAMP,
  purpose TEXT,
  process_type TEXT,
  obstaravatel TEXT,
  obstaravatel_ico TEXT,
  dotknuta_obec TEXT,
  prislusny_organ TEXT,
  legal_basis TEXT,
  snippet TEXT,
  detail_pairs JSONB
);
